[package]
name = "test-unit-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tract-core = { path = "../../core" , version = "=0.21.7" }

[dev-dependencies]
suite-unit = { path = "../suite-unit" }

[build-dependencies]
suite-unit = { path = "../suite-unit" }
