[package]
name = "conform"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
error-chain =  "0"
log = "0.4"
ndarray = "0"
proptest = "0.8"
protobuf = "2.0"
simplelog = "0.5"
tensorflow = "0"
tract = { path = "../../core" }
tract-tensorflow = { path = ".." }
