[package]
name = "jupyter-keras-tract-tf2"
version = "0.1.0"
authors = ["Matthew Alhonte <mattalhonte@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = { git = "https://github.com/rust-lang-nursery/rand" }
tract-core = { path="../../core" }
#tract-tensorflow = { path = "../../tensorflow" }
tract-onnx = { path = "../../onnx" }