[package]
name = "onnx-test-suite"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
edition = "2018"

[dependencies]
bytes = "0.5"
env_logger = "0.7"
fs2 = "0.4"
log = "0.4.6"
prost = "0.6"
tract-onnx = { path = "../../onnx" }

[build-dependencies]
fs2 = "0.4"
