[package]
name = "onnx-test-suite"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
bytes = "1.0.1"
fs2 = "0.4.3"
log = "0.4.14"
prost = "0.10.0"
tract-core = { path = "../../core", features = [ "paranoid_assertions" ] }
tract-nnef = { path = "../../nnef" }
tract-onnx = { path = "../../onnx" }

[features]
onnx_1_4_1 = []
onnx_1_5_0 = []
onnx_1_6_0 = []
onnx_1_7_0 = []
onnx_1_8_1 = []
onnx_1_9_0 = []
onnx_1_10_1 = []
default = [ "onnx_1_10_1" ]

[dev-dependencies]
env_logger = "0.9.0"

[build-dependencies]
fs2 = "0.4.3"
