[package]
name = "example-nnef-mobilenet-v2"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
image = "0.24.1"
bytemuck = "=1.12.2" # on hold till msrv moves 1.60+
tract-nnef = { path = "../../nnef" }
