[package]
name = "example-nnef-mobilenet-v2"
version = "0.19.7-pre"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
image.workspace = true

tract-nnef = { version = "=0.19.7-pre", path = "../../nnef" }
