[package]
name = "example-pytorch-resnet"
version = "0.20.7-pre"
authors = ["Teddy Koker <teddy.koker@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image.workspace = true
tract-onnx.workspace = true
