[package]
name = "debug-utils"
version = "0.19.7-pre"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
edition = "2021"

[workspace]
members = []

[dependencies]
protobuf = "*"
tract-onnx = { path = "../../../onnx" , version = "=0.19.7-pre" }
