site_name: tract-python
repo_name: tract
repo_url: https://github.com/sonos/tract


theme: "material"

nav:
  - Home: index.md
  - ONNX: onnx.md
  - NNEF: nnef.md
  - Inference model: inference_model.md
  - Model: model.md
  - Fact: fact.md
  - Runnable: runnable.md
  - Value: value.md

plugins:
- search
- mike:
    version_selector: true
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          enable_inventory: true
          members_order: source
          separate_signature: false
          show_category_heading: true
          show_if_no_docstring: false
          show_object_full_path: false
          show_signature_annotations: true
          show_submodules: true

extra:
  version:
    provider: mike
