[package]
name = "core-proptest-pulse"
version = "0.19.0-pre"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
tract-hir = { path = "../../hir", version = "=0.19.0" }
tract-pulse = { path = "../../pulse", version = "=0.19.0" }
tract-onnx = { path = "../../onnx", version = "=0.19.0" }
tract-onnx-opl = { path = "../../onnx-opl", version = "=0.19.0" }

[dev-dependencies]
log.workspace = true
proptest.workspace = true
env_logger.workspace = true
