[package]
name = "core-proptest-pulse"
version = "0.20.7-pre"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
tract-core = { path = "../../core", version = "=0.21.8-pre" }
tract-pulse = { path = "../../pulse", version = "=0.21.8-pre" }

[dev-dependencies]
log.workspace = true
proptest.workspace = true
env_logger.workspace = true
