[package]
name = "tf-mobilenet-v2"
version = "0.19.7-pre"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"

[dependencies]
image.workspace = true
tract-tensorflow = { path = "../../tensorflow", version = "=0.19.7-pre" }

[dev-dependencies]
dinghy-test.workspace = true
