[package]
name = "mobilenetv2"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
image = "0.19"
ndarray = "0.12"
tract-core = { path = "../../core" }
tract-tensorflow = { path = "../../tensorflow" }

[dev-dependencies]
dinghy-test = "0.3"
