[package]
name = "tfl-mobilenet-v2-q"
version = "0.20.7-pre"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
image.workspace = true
tract-tflite = { path = "../../tflite", version = "=0.21.7" }

[dev-dependencies]
dinghy-test.workspace = true
