[package]
name = "test-f16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
home.workspace = true
lazy_static.workspace = true
regex.workspace = true
infra = { path = "../infra" }
tract-core = { path = "../../core" , version = "=0.21.3-pre" }
suite-onnx = { path = "../suite-onnx" }
suite-unit = { path = "../suite-unit" }
tract-onnx-opl = { path = "../../onnx-opl", version = "=0.21.3-pre" }

[dev-dependencies]
home.workspace = true
regex.workspace = true
lazy_static.workspace = true
log.workspace = true
tflitec.workspace = true
tract-core = { path = "../../core", version = "=0.21.3-pre" }
tract-nnef = { path = "../../nnef", version = "=0.21.3-pre" }
tract-onnx-opl = { path = "../../onnx-opl", version = "=0.21.3-pre" }
infra = { path = "../infra" }
suite-onnx = { path = "../suite-onnx" }
suite-unit = { path = "../suite-unit" }
