[package]
name = "onnx-proptest"
version = "0.20.7-pre"
edition = "2021"

[workspace]
members = []

[dependencies]
onnx-helpers = "2.2.1"
onnxruntime = { path = "../../../../github/onnxruntime-rs/onnxruntime" }
onnx-pb = "0.1.4"
anyhow = "1.0.56"
prost = "0.11.0"
tract-onnx.workspace = true
proptest = "1.0.0"
