[package]
name = "inceptionv3"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
flate2 = "*"
image = "*"
ndarray = "*"
mio_httpc = "*"
tar = "*"
tfdeploy = { path = "../../core" }
tfdeploy-tf = { path = "../../tfdeploy-tf" }
conform = { path = "../../conform", optional=true }

[dev-dependencies]
criterion = "0.2"
dinghy-test = "0.3"

[features]
tensorflow = [ "conform" ]

[[bench]]
harness = false
name = "inceptionv3"
