[package]
name = "test-tflite"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
lazy_static.workspace = true
regex.workspace = true
infra = { path = "../infra" }
suite-onnx = { path = "../suite-onnx" }
suite-unit = { path = "../suite-unit" }

[dev-dependencies]
regex.workspace = true
lazy_static.workspace = true
log.workspace = true
tflitec.workspace = true
tract-tflite = { path = "../../tflite", version = "=0.20.22-pre" }
tract-onnx-opl = { path = "../../onnx-opl", version = "=0.20.22-pre" }
infra = { path = "../infra" }
suite-onnx = { path = "../suite-onnx" }
suite-unit = { path = "../suite-unit" }
