[package]
name = "jupyter-keras-tract-tf1"
version = "0.20.7-pre"
authors = ["Matthew Alhonte <mattalhonte@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand.workspace = true
tract-core = { path = "../../core", version = "=0.20.7-pre" }
tract-tensorflow = { path = "../../tensorflow", version = "=0.20.7-pre" }
