[package]
name = "cost_model"
version = "0.20.7-pre"
edition = "2021"

[workspace]
members = []

[dependencies]
lazy_static = "1.4.0"
clap = "3.0.7"
scan_fmt = "0.2.6"
rand = "0.8.4"
colorous = "1.0.6"
nu-ansi-term = "0.50"
pbr = "1"
readings-probe = "0.1.4"
tract-linalg = { path="../../linalg", version = "=0.21.7" }
tract-data = { path="../../data", version = "=0.21.7" }
