[package]
name = "cost_model"
version = "0.1.0"
edition = "2021"

[workspace]
members = []

[dependencies]
lazy_static = "1.4.0"
clap = "3.0.7"
scan_fmt = "0.2.6"
rand = "0.8.4"
colorous = "1.0.6"
ansi_term = "0.12.1"
pbr = "1"
readings-probe = "0.1.4"
tract-linalg = { path="../../linalg", version = "0.19.0-alpha.8" }
tract-data = { path="../../data", version = "0.19.0-alpha.13" }
