[package]
name = "suite-onnx"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
bytes.workspace = true
env_logger.workspace = true
fs2.workspace = true
itertools.workspace = true
lazy_static.workspace = true
log.workspace = true
prost.workspace = true
regex.workspace = true 
infra = { path = "../infra" }
tract-core.workspace = true
tract-onnx.workspace = true
tract-hir.workspace = true

[features]
onnx_1_4_1 = []
onnx_1_5_0 = []
onnx_1_6_0 = []
onnx_1_7_0 = []
onnx_1_8_1 = []
onnx_1_9_0 = []
onnx_1_10_2 = []
onnx_1_11_0 = []
onnx_1_12_0 = []
onnx_1_13_0 = []
onnx_1_14_1 = []
onnx_1_15_0 = []
onnx_1_16_2 = []
onnx_1_17_0 = []
onnx_1_18_0 = []
onnx_1_19_1 = []
default = [ "onnx_1_13_0" ]
