[package]
name = "test-nnef-cycle"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
infra = { path = "../infra" }
itertools.workspace = true
lazy_static.workspace = true
suite-onnx = { path = "../suite-onnx" }
suite-unit = { path = "../suite-unit" }
tract-core.workspace = true
tract-transformers.workspace = true

[dev-dependencies]
infra = { path = "../infra" }
itertools.workspace = true
lazy_static.workspace = true
log.workspace = true
suite-onnx = { path = "../suite-onnx" }
suite-unit = { path = "../suite-unit" }
tract-core.workspace = true
tract-transformers.workspace = true
tract-onnx-opl.workspace = true
tract-nnef.workspace = true
