[package]
name = "pytorch-albert-v2"
version = "0.20.7-pre"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anstyle.workspace = true
ndarray.workspace = true
tokenizers.workspace = true
clap_builder = { version = "=4.3.24" }
clap_lex = { version = "=0.5.0" }
tract-onnx = { path = "../../onnx", version = "=0.20.19-pre" }
