[package]
name = "pytorch-albert-v2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.4"
tokenizers = "0.11.0"
tract-onnx = { path = "../../onnx" }
