[package]
name = "pytorch-albert-v2"
version = "0.19.7-pre"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray.workspace = true
tokenizers.workspace = true
tract-onnx = { path = "../../onnx", version = "=0.19.7-pre" }
