[package]
name = "pytorch-albert-v2"
version = "0.20.7-pre"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anstyle.workspace = true
anstyle-parse.workspace = true
anstyle-query.workspace = true
ndarray.workspace = true
tokenizers.workspace = true
clap_builder = { version = "4.4" }
clap_lex = { version = "0.7" }
tract-onnx.workspace = true
