[package]
name = "nnef-inceptionv3"
version = "0.19.0-pre"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
flate2.workspace = true
image.workspace = true
tract-core = { version = "=0.19.0-alpha.19", path = "../../core" }
tract-nnef = { version = "=0.19.0-alpha.19", path = "../../nnef" }

[dev-dependencies]
dinghy-test.workspace = true
env_logger.workspace = true
log.workspace = true
