[package]
name = "lstm_test"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
edition = "2018"

[dependencies]
proptest = "0.10"
tract-tensorflow = { path = "../../tensorflow" }
tract-onnx = { path = "../../onnx" }
