[package]
name = "lstm-proptest-onnx-vs-tf"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
proptest.workspace = true
tract-tensorflow = { path = "../../tensorflow" , version = "0.19.0-alpha.8" }
tract-onnx = { path = "../../onnx" , version = "0.19.0-alpha.8" }
