[package]
name = "tract-cuda"
version = "0.22.1-pre"
license = "MIT OR Apache-2.0"
authors = [
	"Louis Chouraki <louis.chouraki@sonos.com>",
	"Mathieu Poumeyrol <kali@zoy.org>",
]
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/snipsco/tract"
keywords = [ "TensorFlow", "NeuralNetworks", "CUDA" ]
categories = [ "science" ]
autobenches = false
edition = "2024"
rust-version = "1.85"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
anyhow.workspace = true
derive-new.workspace = true
dirs.workspace = true
downcast-rs.workspace = true
liquid.workspace = true
liquid-core.workspace = true
num-traits.workspace = true
tract-core.workspace = true
tract-pulse-opl.workspace = true
tract-transformers.workspace = true
tract-gpu.workspace = true
log.workspace = true
cudarc.workspace = true


[dev-dependencies]
criterion.workspace = true
proptest.workspace = true
rand.workspace = true

[[bench]]
name = "cuda_flash"
harness = false
