[package]
name = "tf-moz-deepspeech"
version = "0.20.7-pre"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
log.workspace = true
tract-tensorflow.workspace = true

[dev-dependencies]
env_logger.workspace = true
