[package]
name = "tf-moz-deepspeech"
version = "0.20.4-pre"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
edition = "2021"
license = "MIT/Apache-2.0"

[dependencies]
log.workspace = true
tract-tensorflow = { path = "../../tensorflow", version = "=0.20.4" }

[dev-dependencies]
env_logger.workspace = true
