[package]
name = "test-conv-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tract-core = { path = "../../core" , version = "=0.20.18" }

[dev-dependencies]
suite-conv = { path = "../suite-conv" }

[build-dependencies]
suite-conv = { path = "../suite-conv" }
