[package]
name = "example-nnef-mobilenet-v2-api"
version = "0.20.7-pre"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT OR Apache-2.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
image.workspace = true
tract-rs.workspace = true
